[workspace]
members = ["crates/*"]
resolver = "2"
default-members = ["crates/rust-pack"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'

